const img = n => `${n}`;
const socialImages = [
  'social-analytics-01.jpeg','social-analytics-02.jpeg','instagram-profile-01.jpeg','instagram-profile-02.jpeg','social-content-01.jpeg','instagram-analytics-01.jpeg','social-analytics-03.jpeg','social-analytics-04.jpeg','social-story-01.jpeg','social-story-02.jpeg','social-story-03.jpeg','event-story-01.jpeg','social-story-04.jpeg','social-story-05.jpeg'
];
const allImages = [
 'social-story-01.jpeg','artist-content-01.jpeg','social-story-02.jpeg','social-story-03.jpeg','event-bts-01.jpeg','event-story-01.jpeg','event-story-02.jpeg','campaign-poster-01.jpeg','saint-location-01.jpeg','saint-location-02.jpeg','saint-location-03.jpeg','saint-location-04.jpeg','saint-location-05.jpeg','music-platform-evidence-01.png','music-platform-evidence-02.png','music-platform-evidence-03.png','music-platform-evidence-04.png','social-story-04.jpeg','social-story-05.jpeg','event-crowd-01.jpeg','artist-performance-01.jpeg','youtube-presence.jpeg','event-crowd-02.jpeg','event-story-03.jpeg','behind-scenes-01.jpeg'
];
function gallery(el, arr){arr.forEach((name,i)=>{const b=document.createElement('button');b.className='gallery-item';b.innerHTML=`<img loading="lazy" src="${img(name)}" alt="Portfolio evidence ${i+1}">`;b.onclick=()=>openImage(name);el.appendChild(b)})}
document.querySelectorAll('.gallery').forEach((el)=>gallery(el,el.classList.contains('all-gallery')?allImages:socialImages));
const modal=document.getElementById('modal'), content=document.getElementById('modal-content');
function openImage(name){content.innerHTML=`<img src="${img(name)}" style="width:100%;max-height:76vh;object-fit:contain;border-radius:12px" alt="Portfolio evidence">`;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
function openCase(id){
 let html='';
 const common=`<p>Selected evidence is presented as a professional case study. Original source files and sensitive/internal material remain in the private evidence archive supplied with this project.</p>`;
 if(id==='research') html=`<p class="eyebrow">RESEARCH • STRATEGY • INVESTMENT</p><h3>Entertainment Investment & Partnership Strategy</h3>${common}<div><span class="modal-stat">3 proposal documents</span><span class="modal-stat">Investor research</span><span class="modal-stat">Partnership packages</span><span class="modal-stat">Pitch planning</span></div><p>The work covers a Jamie Gold partnership proposal, a broader J Entertainment strategic investment proposal, and an investor/brand sponsorship mobilization plan. The materials include funding allocations, partnership structures, target prospects, value propositions, reporting concepts and recommended next steps.</p>`;
 if(id==='artist') html=`<p class="eyebrow">ENTERTAINMENT • ARTIST SUPPORT</p><h3>Jamie Gold — Artist & Creative Support</h3>${common}<div><span class="modal-stat">Artist promotion</span><span class="modal-stat">Media materials</span><span class="modal-stat">Events</span><span class="modal-stat">Music projects</span></div><p>Portfolio evidence includes the artist media kit, the “Saint” project document and visual production material, event and behind-the-scenes imagery, promotional assets and platform presence evidence.</p><div class="modal-gallery">${['saint-location-01.jpeg','saint-location-02.jpeg','saint-location-03.jpeg','saint-location-04.jpeg','saint-location-05.jpeg','campaign-poster-01.jpeg'].map(n=>`<img src="${img(n)}" alt="Artist project evidence">`).join('')}</div>`;
 if(id==='social') html=`<p class="eyebrow">SOCIAL MEDIA • ANALYTICS</p><h3>Social Media Management & Performance</h3>${common}<div><span class="modal-stat">Instagram: 296K+ followers shown</span><span class="modal-stat">TikTok: 40.7K followers shown</span><span class="modal-stat">TikTok: 139.8K post views</span><span class="modal-stat">Top visible Instagram post: 1.3M views</span></div><p>Instagram evidence includes views, interactions, audience demographics and follower movement. TikTok evidence includes views, likes, comments, shares, traffic sources, follower growth and top content.</p>`;
 if(id==='admin') html=`<p class="eyebrow">ADMINISTRATION • EXECUTIVE SUPPORT</p><h3>Executive Administration & Coordination</h3>${common}<div><span class="modal-stat">Calendar & scheduling</span><span class="modal-stat">Inbox & correspondence</span><span class="modal-stat">Travel & accommodation</span><span class="modal-stat">Meetings & minutes</span><span class="modal-stat">Research & reports</span></div><p>Experience includes full travel itinerary handling for Jamie Gold, accommodation coordination, meeting documentation, research, reports, executive calendars, communications and follow-up. Where original itinerary files were lost, the portfolio describes the experience without fabricating missing evidence.</p>`;
 if(id==='it') html=`<p class="eyebrow">IT • HARDWARE</p><h3>Computer Inventory & Hardware Identification</h3>${common}<div><span class="modal-stat">Motherboard identification</span><span class="modal-stat">External I/O</span><span class="modal-stat">Technical documentation</span><span class="modal-stat">PC hardware studies</span></div><p>The project documents motherboard components and external connectors including CPU power, CPU socket, fan connector, ATX main power, memory, PCIe, CMOS, M.2, USB, DisplayPort, HDMI, Ethernet and audio.</p>`;
 content.innerHTML=html;modal.classList.add('open');modal.setAttribute('aria-hidden','false')
}
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openCase(b.dataset.open)));
document.querySelector('.close').onclick=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')};document.querySelector('.modal-backdrop').onclick=()=>document.querySelector('.close').click();document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector('.close').click()});
const menu=document.querySelector('.menu');menu.onclick=()=>{const n=document.querySelector('.nav-links');n.style.display=n.style.display==='flex'?'none':'flex';n.style.position='absolute';n.style.right='14px';n.style.top='64px';n.style.background='var(--paper)';n.style.padding='16px';n.style.border='1px solid var(--line)';n.style.borderRadius='14px';n.style.flexDirection='column'};
